---
abstract: 'RC4 library based on OpenSSL'
author:
  - 'Tokuhiro Matsuno <tokuhirom gmail.com>'
build_requires:
  ExtUtils::CBuilder: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-RC4
provides:
  Crypt::OpenSSL::RC4:
    file: lib/Crypt/OpenSSL/RC4.pm
    version: 0.03
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.03
