---
abstract: 'RC4 library based on OpenSSL'
author:
  - unknown
build_requires:
  ExtUtils::CBuilder: 0
configure_requires:
  Devel::CheckLib: 0.99
  Module::Build: 0.4004
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-RC4
provides:
  Crypt::OpenSSL::RC4:
    file: lib/Crypt/OpenSSL/RC4.pm
    version: 0.04
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tokuhirom/Crypt-OpenSSL-RC4
version: 0.04
x_test_requires:
  Test::More: 0.98
